name: Integration test

on: push

jobs:
  integration-test-uninstall:
    name: Uninstall
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed="$(ct list-changed --config ct.yaml)"
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.2.0

      - name: Run 'helm install'
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm upgrade --install \
            posthog ./charts/posthog \
            --debug \
            --timeout 10m \
            --set "cloud=private" \
            --wait \
            --wait-for-jobs

      - name: Run 'helm uninstall'
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm uninstall \
            posthog \
            --debug \
            --timeout 10m \
            --wait
